services:
  app:
    build: .
    container_name: flurbix-app
    env_file:
      - flurbix-app/.env
    environment:
      - NODE_ENV=production
    expose:
      - "5173"
    restart: unless-stopped
    networks:
      - webnet
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  webnet:
    external: true
